version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql


  app:
    build: .
    command: node app.js
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
